### ISSUE TITLE
Docs: circular reference wrt system registration

### ISSUE THREAD

**Issue by jcorbin** [fritzy/ape-ecs#32]
So [docs/World.md](//github.com/fritzy/ape-ecs/blob/master/docs/World.md#registersystem) says "👀 See " the system docs for details on registering and running.

Which [docs/System.md](//github.com/fritzy/ape-ecs/blob/master/docs/System.md#registering-and-running) section says "👀 See " the world docs.

I've been had! Guess I'll have to make do with reading the source for now ;-)

**Comment by fritzy** [comment]
I didn't mean this to run you in circles. I'll change the wording a bit. What information is missing?
