### ISSUE TITLE
Having trouble getting subscribe() working for Component changes

### ISSUE THREAD

**Issue by atduskgreg** [fritzy/ape-ecs#44]
I'm trying to use the Component change subscriptions system described [here](https://github.com/fritzy/ape-ecs/blob/master/docs/System.md#subscribe) and I'm having trouble subscribing to change events.

I've got [my Position component](https://github.com/atduskgreg/fictional-octo-robot/blob/main/js/components/position.js) on which I've set

`this.changeEvents = true;`

in the constructor. I only change the position's data by calling its update method [here](https://github.com/atduskgreg/fictional-octo-robot/blob/4810a03cfc906a234320eb066c512bdf25ce4e0f/js/systems/path_find.js#L36).

Then I subscribe to the events in  my [OnMoveEventHandler system](https://github.com/atduskgreg/fictional-octo-robot/blob/main/js/systems/on_move_event_handler.js).

I'm successfully seeing add events but I'm not seeing any change events. 

Is this a bug or am I missing something in configuring this?

**Comment by atduskgreg** [comment]
FWIW I think the problem may have something with the constructor or its invocation. calling `this.changeEvents = true` in the constructor didn't actually cause the change events get sent, but calling `this.constructor.changeEvents = true` inside of init() did:

`class Position extends ApeECS.Component {
    
    constructor(){
        super();
 
        this.changeEvents = true; // this doesn't do anything
        this.x = 0;
        this.y = 0;
    }
    init(values)
    {
        this.x = values.x;
        this.y = values.y;
        this.constructor.changeEvents = true; // this is necessary
    }

}
`

**Comment by fritzy** [comment]
Right, as the documents show, changeEvents is a static property, not an instance property.
