### ISSUE TITLE
Init System with Custom Parameters

### ISSUE THREAD

**Issue by hanshamm** [fritzy/ape-ecs#45]
Hi, 
I would like to suggest a small change in the System creation process to have a more flexible solution for Systems with custom parameters.

Example for a system with custom parameters:
```
const world = new EcsApe.World()
world.registerSystem('render', new SystemWithCustomParameters(world, 1, 2, 3) )
```
where: 
``` 
class SystemWithCustomParameters extends ApeECS.System {
  constructor (world, param1, param2, param3) {
    super(world)
    this.customInit(param1, param2, param3)
  }

  customInit(parameters) {
      // do stuff with parameters here
  }
}

``` 
The `init()` that `ApeECS.System` is offering cannot be used here. My suggestion would be to pass through additional parameters from the constructor, such as:

```
class System {

  constructor(world, ...args) {
    this.world = world
    // ..
    this.init(...args)
  }  
 }
```
This would allow to have all additional parameters available in the `init()` function, if needed. Please have a look also my js-fiddle I created here: https://jsfiddle.net/cv85mezq/106/

If we change the `world.registerSystem` as well, like so:
```
registerSystem(group, system, ...args) {

    if (typeof system === 'function') {
      system = new system(this, ...args);
    }
    if (!this.systems.has(group)) {
      this.systems.set(group, new Set());
    }
    this.systems.get(group).add(system);
    return system;
  }
```

we could even let the World create the System with custom parameters like this:

```
world.registerSystem('render', SystemWithCustomParameters, 1, 2, 3)
```

What do you think of this?

**Comment by fritzy** [comment]
I implemented this as you suggested, and I made registerSystem take an optional array for those parameters as well.
https://github.com/fritzy/ape-ecs/blob/portability/docs/World.md#registersystem
