### ISSUE TITLE
fromAny seems to override fromAll?

### ISSUE THREAD

**Issue by vmwxiong** [fritzy/ape-ecs#53]
The docs state that if both are declared, a query should not match unless all components in `fromAll` are satisfied in addition to having one or more components from `fromAny`. In practice, it seems like including a `fromAny` will ignore the `fromAll` requirement, at least when checking for a tag that gets added/removed.

**Comment by fritzy** [comment]
fromAny and fromAll add to results and don't filter. They don't interact with other results at all. `only` and `not` filter out results from the "from" declarations. Queries are declarative, and ignore order.

**Comment by vmwxiong** [comment]
Hmmm, that makes sense, but I think the documentation might be misleading:

https://github.com/fritzy/ape-ecs/blob/master/docs/Query.md#fromany

```js
//must have Character Component type or tag and must have one or more of Sprite, Image, or New.
const query = world.createQuery().fromAll('Character').fromAny('Sprite', 'Image', 'New');
```

From what you said, it sounds like it should be "OR must have one or more of Sprite, Image, or New", rather than AND.
