### ISSUE TITLE
Sharing Queries?

### ISSUE THREAD

**Issue by vmwxiong** [fritzy/ape-ecs#54]
If two systems happen to have the same criteria for a query, is there currently a way to share the query?

`this.world.systems.get("OtherSystem").myPersistedQuery.execute()`?

Seems like a bad idea to have the systems know about one another, but it would be nice to be able to reuse the same underlying query somehow since it seems like adding a lot of persisted queries is not great for performance. Maybe queries could be given an id to access with `world.getQuery(id)`?

**Comment by fritzy** [comment]
Persisted queries are tied into the system logically for their lifecycle. I'm not considering this feature at this time.
