### ISSUE TITLE
entity.getObject can return a circular reference

### ISSUE THREAD

**Issue by vmwxiong** [fritzy/ape-ecs#55]
Not sure if it's necessarily an issue, but you can't just JSON.stringify the result of an entity.getObject because it might have circular references.

This is easy to do if you create a value on a component which is an array of entities.

**Comment by fritzy** [comment]
That's what `EntityRef` and more specifically to your example `EntitySet` are for. There's no need to reference entities directly

**Comment by vmwxiong** [comment]
ah, thanks! Totally didn't realize this was a thing, makes a ton of sense. Might be worth highlighting an example of using this in the main README even? Seems pretty important to know not to make vanilla arrays of entities, and it was easy to overlook.
