### ISSUE TITLE
World Cleanup/Deletion?

### ISSUE THREAD

**Issue by vmwxiong** [fritzy/ape-ecs#56]
What's the recommended way to clean up the world once you're done with it in a way that avoids memory leaks?

Currently I'm doing:
```js
  for (const entity of world.entities.values()) {
    entity.destroy();
  }
  world.entities.clear();
```

**Comment by fritzy** [comment]
That last line shouldn't be necessary. If everything isn't being cleaned up properly upon destruction of an entity (or all entities) then we have a bug. Let me know. Thanks.
