### ISSUE TITLE
Loading world and jumping into a given point in the system stack?

### ISSUE THREAD

**Issue by vmwxiong** [fritzy/ape-ecs#57]
This is a bit of an interesting problem. Let's say I have 5 systems running in order. If I save the world within the 3rd system, then shut everything down, the next time I load the world, I want to somehow jump right back into the system stack at the 3rd system, so that the first two systems don't get processed twice within the same tick.

What do you think of adding a variation on `runSystems` for this purpose?

```js
world.runSystemsFromSystem("default", ThirdSystem);
```

**Comment by vmwxiong** [comment]
Looking through some more of the code, would it make sense for `World.getObject()` to serialize some state of the World and Systems as well?

Would be a big breaking change, but it might make sense to also serialize `system.lastTick` and `world.currentTick`, so you when you load a world again, you could keep track of which systems had already processed the current tick, and where you could pick up.

**Comment by martinemmert** [comment]
I tried to develop an idea when it is safe and useful to save the state in between the systems instead of after a whole world update. Care to elaborate, why you need such a thing?

**Comment by vmwxiong** [comment]
Pretty specific, but I'm writing a game where the systems often want to sort of pause the whole simulation at various points and go back to the user for a specific input. It's actually all serverless too, so I need to be able to save the world and then rehydrate it once the user comes back with their input in however long it takes.

**Comment by martinemmert** [comment]
Thanks. Now I understand your case. Here is my take on ECS. Maybe it helps:
- the entities act as stores, shaped by components
- the state is transformed by the systems
- a system works with the information it has
- if the requested information is not available, the system is skipped

After reading your explanation, the concept of finite state machines came into my mind.

So what I would try the following:
- have an FMS that holds the state of the user
- your systems process the game world, including the current state of the user
- if a specific input is needed, your user is set into the waiting state
- your systems process the game world, excluding the waiting user
- if the specific input is given, the user transitions into the next state

If time is a driving factor for your systems simulation, pause it while the specific user input is requested.

Hope this helps 👍

**Comment by vmwxiong** [comment]
Yeah that's basically what I'm doing now, but I've had to add quite a lot of code to everything in order to check this state now. If I could just pick up where I left off in the systems processing order, it would save me a lot of boilerplate lines of code by changing the execution flow rather than needing to store and read a ton of state

**Comment by fritzy** [comment]
You're in complete control of which systems run and when you can set the world.currentTick to whatever you want. You can also put the results of getObject into a container that includes the currentTick. In the future, when Ape gets some network support, we may have more specifics around state loading and restoring.

For now, feel free to solve this problem for yourself outside of the lib. It shouldn't be too hard to keep track of which system you left off on and what the currentTick was and jump back in upon restoring state.
