### ISSUE TITLE
genPrefix doesn't do anything at all

### ISSUE THREAD

**Issue by martinemmert** [fritzy/ape-ecs#59]
https://github.com/fritzy/ape-ecs/blob/d719d83c38e6fe8770fe058ee6418402d6959fe5/src/util.js#L10-L12

Well, kind of a bummer but - this method doesn't change the prefix currently.

**Comment by martinemmert** [comment]
My current take on this is:

```
 genPrefix() {
    this.prefix = uuid().substr(0, 8);
  }
```

I'll create a pull request, as soon as possible.

**Comment by fritzy** [comment]
Sure, historically it did more. I don't know that it _needs_ to do anything though?

**Comment by martinemmert** [comment]
It should set the `prefix`. Currently, it is a noop.

**Comment by martinemmert** [comment]
relates to #61
