### ISSUE TITLE
Where to check hasSet's cname is correct?

### ISSUE THREAD

**Issue by odys-z** [fritzy/ape-ecs#6]
Hi everyone,

I'm trying to modify the source to add some Query logic like "any" in addition to "has".

While testing, I got error message like this:

    TypeError: hasSet[0] is not iterable

Which is reported at 

    QueryCache.initial() {
        if (hasSet && hasSet.length > 0) {
            // an undefined been pushed into hasSet, length == 1
            results = new Set([...hasSet[0]]); 
        }
    }

This is because i had misspelled the component's name. Since the message is confusing, I think it's better to check and throw error. But the ECS.entityComponents is a JS Map.

So is wrapping this field as a class/structure the correct way to do this?

It's not wise to check every time as this only happens the first time.

BTW, if the logic extending is helpful, i'm every happy to fork and file a pull request.

**Comment by fritzy** [comment]
@odys-z I'd love a pull request, thanks!

**Comment by odys-z** [comment]
hi, sorry for late.
Some questions about it:
1. In version 0.5.2, there is new function added, entity tag. What's the relationship to component "has"? Any docs / tutorials about this concept?
2. I have previously thinking that "has" means all entities in query results (arg of update()) have all the components and without others, e.g.
 e = {c1, c2}, f = {c1, c2, c3}, 
=> result = [e]
I think i'v verified this with test case, but it's not the case now. 
So I'v added a new logic, iffall, supporting the above case. This must messed things up.
Does "has" is used for this:
d = {c1}, e = {c1, c2}, f = {c1, c2, c3}, 
=> result = [e, f] ?

**Comment by fritzy** [comment]
This has been redone and should more clear now. We're nearing 1.0.
