### ISSUE TITLE
Calling destroy twice has very odd effects

### ISSUE THREAD

**Issue by JackStouffer** [fritzy/ape-ecs#66]
I was accidentally calling `world.removeEntity` and then `entity.destroy` in sequence.

```ts
function removeEntity(ecs: World, entity: Entity) {
    const graphicData = entity.getOne(GraphicsComponent);
    // delete the sprite from memory here

    ecs.removeEntity(entity);
    entity.destroy();
}
```

I noticed that doing this led to the entity's components not being cleared before it was entered into the entity pool. As I was stepping through the code I could clearly see that my entities were in the pool and all of its components were still defined.

Later on in the code, I called `createEntity` and the latest destroyed entity would be popped from the pool, with all of its original components. So the two component definitions would be overlaid on top of each other.

This is very surprising. I would expect the second call would be a no-op or would throw an error saying `this entity is already destroyed`.

**Comment by fritzy** [comment]
I wasn't able to reproduce this with a test. https://github.com/fritzy/ape-ecs/blob/9dcbcd2fbd238da5a67eae0b1058dfcda5700b3e/tests/index.ts#L1918-L1970

However, you're right, that `destroy()` should no-op the second time, so I made that fix (`world.removeEntity(e)` also calls `destroy()` on the entity).

Is there some other way that I can reproduce the problem in the previous commit reliably?

In any case, ape-ecs@1.3.1 has been published.
