### ISSUE TITLE
Is it better for CoreProperties collision detection to happen earlier?

### ISSUE THREAD

**Issue by esromneb** [fritzy/ape-ecs#9]
I'm not positive, but it seems like a "CoreProperties collision" is only detected at "run" time, but this error could be thrown much earlier when `registerComponent()` is called.

The error I get is:

```bash
component.js:52 Uncaught Error: Cannot override property in Component definition: id
```

(I will just have to live with the fact that I can't use `id`)

**Comment by fritzy** [comment]
I've got an entirely new version of component coming, but this is a good point. I'll make sure it is addressed going forward.

**Comment by fritzy** [comment]
Should no longer be an issue.
